apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: rabbitmq
spec:
  serviceName: rabbitmq
  replicas: 3
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
      - name: rabbitmq
        image: eurobankgr/rabbitmq-autocluster
        ports:
          - containerPort: 5672
            name: rabbitmq-amqp
          - containerPort: 4369
            name: rabbitmq-epmd
          - containerPort: 5671
            name: rabbitmq-amqps
          - containerPort: 15672
            name: rabbitmq-mgmt
          - containerPort: 25672
            name: rabbitmq-node
        livenessProbe:
          exec:
            command: ["rabbitmqctl", "node_health_check"]
          initialDelaySeconds: 5
          timeoutSeconds: 3
          periodSeconds: 15
        imagePullPolicy: Always
        volumeMounts:
        - mountPath: /var/lib/rabbitmq
          name: rabbitmq
        env:
        - name: HOSTNAME
          valueFrom:
           fieldRef:
            fieldPath: status.podIP
        - name: AUTOCLUSTER_TYPE
          value: "k8s"
        - name: K8S_SERVICE_NAME
          valueFrom:
           fieldRef:
            fieldPath: metadata.labels.app
        - name: RABBITMQ_NODENAME
          value: "rabbitmq@$(HOSTNAME)"
        - name: RABBITMQ_USE_LONGNAME
          value: "true"
        - name: RABBITMQ_DEFAULT_USER
          value: "admin"
        - name: RABBITMQ_DEFAULT_PASS
          valueFrom:
            secretKeyRef:
              name: rabbitmq
              key: default-password
        - name: RABBITMQ_ERLANG_COOKIE
          valueFrom:
            secretKeyRef:
              name: rabbitmq
              key: erlang-cookie
      volumes:
        - name : rabbitmq
          emptyDir:
            medium: Memory
